// Code generated by "messagestringer -file=tui.go -prefix=msg"; DO NOT EDIT.

package tui

import "fmt"

func (msg msgInitialized) String() string {
	return fmt.Sprintf("[msgInitialized %#v]", msg)
}

func (msg msgWrite) String() string {
	return fmt.Sprintf("[msgWrite %#v]", msg)
}

