[[task]]
  id = "dev"
  description = "Builds and runs the package, restarting when any go file is changed."
  type = "long"
  triggers = ["build"]
  env = { PORT = "8000" }
  cmd = "./example"

[[task]]
  id = "build"
  description = "Builds the package."
  type = "short"
  watch = ["**/*.go"]
  cmd = "go build ."

