before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/run
    ldflags:
      - -s -w -X 'github.com/amonks/run.Version={{.Version}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    files:
      - LICENSE.*
      - CONTRIBUTORS.*
      - CREDITS.*
      - docs/*

    # NOTE
    # ensure the OS and Arch values match (uname -m) and (uname -a).
    name_template: >-
      run_
      {{- if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{- title .Os }}
      {{- end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{- .Arch }}
      {{- end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
