// Code generated by "stringer -type RunType"; DO NOT EDIT.

package runner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[runTypeInvalid-0]
	_ = x[RunTypeShort-1]
	_ = x[RunTypeLong-2]
}

const _RunType_name = "runTypeInvalidRunTypeShortRunTypeLong"

var _RunType_index = [...]uint8{0, 14, 26, 37}

func (i RunType) String() string {
	if i < 0 || i >= RunType(len(_RunType_index)-1) {
		return "RunType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunType_name[_RunType_index[i]:_RunType_index[i+1]]
}
