// Code generated by "stringer -type taskState"; DO NOT EDIT.

package run

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[taskStateNotStarted-0]
	_ = x[taskStateRunning-1]
	_ = x[taskStateRestarting-2]
	_ = x[taskStateStopping-3]
	_ = x[taskStateStopped-4]
}

const _taskState_name = "taskStateNotStartedtaskStateRunningtaskStateRestartingtaskStateStoppingtaskStateStopped"

var _taskState_index = [...]uint8{0, 19, 35, 54, 71, 87}

func (i taskState) String() string {
	if i < 0 || i >= taskState(len(_taskState_index)-1) {
		return "taskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _taskState_name[_taskState_index[i]:_taskState_index[i+1]]
}
