[[task]]
  id = "install"
  type = "short"
  dependencies = ["generate"]
  cmd = "go install ./cmd/runner"

[[task]]
  id = "generate"
  type = "short"
  cmd = "go generate ./..."

[[task]]
  id = "screenshots"
  type = "short"
  dependencies = [
    "screenshot-tui",
    "screenshot-printer",
    "screenshot-nontty",
  ]
  cmd = """
    echo cleaning up
    echo "" > example/src.js
    echo "" > example/src.css
    echo "" > example/dist.js
    echo "" > example/dist.css
  """

[[task]]
  id = "screenshot-tui"
  type = "short"
  dependencies = ["install"]
  cmd = """
    cd example
    vhs ../screenshots/tui.tape
    mv tui.gif ../screenshots/
  """

[[task]]
  id = "screenshot-printer"
  type = "short"
  dependencies = ["install"]
  cmd = """
    cd example
    vhs ../screenshots/printer.tape
    mv printer.gif ../screenshots/
  """

[[task]]
  id = "screenshot-nontty"
  type = "short"
  dependencies = ["install"]
  cmd = """
    cd example
    vhs ../screenshots/nontty.tape
    mv nontty.gif ../screenshots/
  """

[[task]]
  id = "overwrite-snapshots"
  type = "short"
  cmd = """
    cd testdata/examples
    for d in * ; do
      if test -f $d/fail.log ; then
        echo overwriting $d
        mv $d/fail.log $d/out.log
      fi
    done
  """

[[task]]
  id = "generate-docs"
  type = "short"
  cmd = """
    godoc -http=0.0.0.0:3335 &

    sha=$(git rev-parse --short HEAD)

    for (( ; ; )); do
      sleep 0.5
      if [[ $(curl -so /dev/null -w '%{http_code}' "http://localhost:3335/pkg/github.com/amonks/runner/") -eq 200 ]]; then
        break
      fi
    done

    wget --quiet --mirror --page-requisites --no-parent http://localhost:3335/pkg/github.com/amonks/runner

    cd localhost:3335
    mv pkg/github.com/amonks/runner index.html
    rm -r pkg
    sed -i -e 's%"/pkg%"https://pkg.go.dev/pkg%g' index.html
    sed -i -e 's%"/lib%"/runner/lib%g' index.html
    sed -i -e '/topbar/,+11d' index.html
    sed -i -e '/footer/,+8d' index.html
    rm index.html-e
    cd ..

    rm -r docs
    mv localhost:3335 docs
  """
