// Code generated by "stringer -type RunnerMode"; DO NOT EDIT.

package runner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[runnerModeInvalid-0]
	_ = x[RunnerModeKeepalive-1]
	_ = x[RunnerModeExit-2]
}

const _RunnerMode_name = "runnerModeInvalidRunnerModeKeepaliveRunnerModeExit"

var _RunnerMode_index = [...]uint8{0, 17, 36, 50}

func (i RunnerMode) String() string {
	if i < 0 || i >= RunnerMode(len(_RunnerMode_index)-1) {
		return "RunnerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunnerMode_name[_RunnerMode_index[i]:_RunnerMode_index[i+1]]
}
