// Code generated by "messagestringer -file=runner.go -prefix=msg"; DO NOT EDIT.

package runner

import "fmt"

func (msg msgActivateSubtree) String() string {
	return fmt.Sprintf("[msgActivateSubtree %#v]", msg)
}

func (msg msgDeactivateSubtree) String() string {
	return fmt.Sprintf("[msgDeactivateSubtree %#v]", msg)
}

func (msg msgRunTask) String() string {
	return fmt.Sprintf("[msgRunTask %#v]", msg)
}

func (msg msgTaskReady) String() string {
	return fmt.Sprintf("[msgTaskReady %#v]", msg)
}

func (msg msgInvalidateTask) String() string {
	return fmt.Sprintf("[msgInvalidateTask %#v]", msg)
}

func (msg msgRunnerDone) String() string {
	return fmt.Sprintf("[msgRunnerDone %#v]", msg)
}

func (msg msgTaskExit) String() string {
	return fmt.Sprintf("[msgTaskExit %#v]", msg)
}

func (msg msgFSEvent) String() string {
	return fmt.Sprintf("[msgFSEvent %#v]", msg)
}

