name: Publish release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: macos-14
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set up go"
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: "Publish"
        run: ./publish.bash
        env:
          GH_TOKEN: ${{ github.token }}
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
          APPLE_DEVELOPER_PASSWORD: ${{ secrets.APPLE_DEVELOPER_PASSWORD }}
          APPLE_DEVELOPER_TEAM: ${{ secrets.APPLE_DEVELOPER_TEAM }}
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
